// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBP5pnky1VXbHmSDR-0chPSZIdVzU3Djs',
    appId: '1:84746666973:web:9b573b51ff668a1f0b6c34',
    messagingSenderId: '84746666973',
    projectId: 'vybe-bata',
    authDomain: 'vybe-bata.firebaseapp.com',
    storageBucket: 'vybe-bata.firebasestorage.app',
    measurementId: 'G-8ML6FVEY7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsbH9YtjJc5sehy0S3Yj_zxfwDZoZtriU',
    appId: '1:84746666973:android:8fb5a4e7c37ec19c0b6c34',
    messagingSenderId: '84746666973',
    projectId: 'vybe-bata',
    storageBucket: 'vybe-bata.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWMQAmFmyl3oofc3jElmjBp1_t3HDXed4',
    appId: '1:84746666973:ios:85e36ef7c28fac8f0b6c34',
    messagingSenderId: '84746666973',
    projectId: 'vybe-bata',
    storageBucket: 'vybe-bata.firebasestorage.app',
    iosBundleId: 'com.example.vybe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWMQAmFmyl3oofc3jElmjBp1_t3HDXed4',
    appId: '1:84746666973:ios:85e36ef7c28fac8f0b6c34',
    messagingSenderId: '84746666973',
    projectId: 'vybe-bata',
    storageBucket: 'vybe-bata.firebasestorage.app',
    iosBundleId: 'com.example.vybe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBP5pnky1VXbHmSDR-0chPSZIdVzU3Djs',
    appId: '1:84746666973:web:804f1075ac245a270b6c34',
    messagingSenderId: '84746666973',
    projectId: 'vybe-bata',
    authDomain: 'vybe-bata.firebaseapp.com',
    storageBucket: 'vybe-bata.firebasestorage.app',
    measurementId: 'G-1BQLF89TPX',
  );
}
