"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.onReviewUpdated = exports.onReviewDeleted = exports.onReviewCreated = exports.onFavoriteDeleted = exports.onFavoriteCreated = exports.deleteUser = exports.verifyIdentity = exports.kakaoLogin = exports.naverLogin = exports.phoneLogin = exports.checkPhoneDuplicate = exports.onUserCreated = void 0;
const admin = require("firebase-admin");
admin.initializeApp();
var on_user_created_1 = require("./auth/on_user_created");
Object.defineProperty(exports, "onUserCreated", { enumerable: true, get: function () { return on_user_created_1.onUserCreated; } });
var check_phone_duplicate_1 = require("./auth/check_phone_duplicate");
Object.defineProperty(exports, "checkPhoneDuplicate", { enumerable: true, get: function () { return check_phone_duplicate_1.checkPhoneDuplicate; } });
var phone_login_1 = require("./auth/phone_login");
Object.defineProperty(exports, "phoneLogin", { enumerable: true, get: function () { return phone_login_1.phoneLogin; } });
var naver_login_1 = require("./auth/naver_login");
Object.defineProperty(exports, "naverLogin", { enumerable: true, get: function () { return naver_login_1.naverLogin; } });
var kakao_login_1 = require("./auth/kakao_login");
Object.defineProperty(exports, "kakaoLogin", { enumerable: true, get: function () { return kakao_login_1.kakaoLogin; } });
var verify_identity_1 = require("./auth/verify_identity");
Object.defineProperty(exports, "verifyIdentity", { enumerable: true, get: function () { return verify_identity_1.verifyIdentity; } });
var delete_user_1 = require("./auth/delete_user");
Object.defineProperty(exports, "deleteUser", { enumerable: true, get: function () { return delete_user_1.deleteUser; } });
var on_favorite_created_1 = require("./favorites/on_favorite_created");
Object.defineProperty(exports, "onFavoriteCreated", { enumerable: true, get: function () { return on_favorite_created_1.onFavoriteCreated; } });
var on_favorite_deleted_1 = require("./favorites/on_favorite_deleted");
Object.defineProperty(exports, "onFavoriteDeleted", { enumerable: true, get: function () { return on_favorite_deleted_1.onFavoriteDeleted; } });
var on_review_created_1 = require("./reviews/on_review_created");
Object.defineProperty(exports, "onReviewCreated", { enumerable: true, get: function () { return on_review_created_1.onReviewCreated; } });
var on_review_deleted_1 = require("./reviews/on_review_deleted");
Object.defineProperty(exports, "onReviewDeleted", { enumerable: true, get: function () { return on_review_deleted_1.onReviewDeleted; } });
var on_review_updated_1 = require("./reviews/on_review_updated");
Object.defineProperty(exports, "onReviewUpdated", { enumerable: true, get: function () { return on_review_updated_1.onReviewUpdated; } });
//# sourceMappingURL=index.js.map